swagger: "2.0"
info:
  version: "0.0.1"
  title: Fortuna Fiskekort API
# during dev, should point to your local machine
host: 10.5.90.61:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users:
    # binds a127 app logic to a route
    x-swagger-router-controller: user
    get:
      description: Gets the user list
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetUsersResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Add an user
      # info to be stored
      operationId: save
      parameters:
        - name: username
          description: user properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
            
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /user/{id}:
    x-swagger-router-controller: user
    get:
      description: Gets a specified user
      operationId: getOne
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    put:
      description: Update an user
      operationId: update
      parameters:
        - name: id
          description: User ID
          type: string
          in: path
          required: true
        - name: username
          description: User properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
    delete:
      description: Delete an user
      operationId: delUser
      parameters:
        - name: id
          description: User ID
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User: 
    type: object
    properties:
      username:
        type: string
        description: User name
      phone:
        type: string
        description: Phone number
    required:
      - username
      - phone
  
  GetUsersResponse:
    required:
      - users
    properties:
      users:
        # array of users
        type: array
        items:
          type: object
          properties:
           id:
              type: string
           username:
              type: string
              
  GetUserResponse:
    required:
      - id
      - username
      - phone
    properties:
      id:
        type: string
      username:
        type: string
      phone:
        type: string
  
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description