swagger: "2.0"
info:
  version: "0.0.1"
  title: Fortuna Fiskekort API
# during dev, should point to your local machine
host: 10.5.90.61:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  $ref: ./paths/index.yaml

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  $ref: ./definitions/index.yaml
