swagger: "2.0"
info:
  version: "0.0.1"
  title: Fortuna Fiskekort API
# during dev, should point to your local machine
host: 10.5.90.61:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  $ref: ./paths/index.yaml

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User: 
    type: object
    properties:
      username:
        type: string
        description: User name
    required:
      - username
  
  GetUsersResponse:
    required:
      - users
    properties:
      users:
        # array of users
        type: array
        items:
          type: object
          properties:
           id:
              type: string
           username:
              type: string
              
  GetUserResponse:
    required:
      - id
      - username
    properties:
      id:
        type: string
      username:
        type: string
  
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description